export const RECEIVE_USER = 'receive_user'
export const RECEIVE_TOKEN = 'receive_token'
export const GET_GOODS = 'get_goods'
export const ADD_GOODS = 'add_goods'
export const DELE_GOODS = 'dele_goods'
export const UPDATE_GOODS = 'update_goods'
export const RECEIVE_COACHES = 'receive_coaches'
export const ADD_COACH = 'add_coach'
export const UPDATE_COACH = 'update_coach'
export const DELETE_COACH= 'delete_coach'
export const SEARCH_COACH= 'search_Coach'
export const RECEIVE_ORDERS = 'receive_orders'
export const RECEIVE_STAFF = 'receive_staff'
export const GET_CLASS = 'receive_class'
//更新课程信息
export const UPDATE_CLASS = 'update_class'
// 增加课程信息 
export const ADD_CLASS = 'add_class'
// 删除课程信息
export const DELETE_CLASS = 'delete_class'