export const RECEIVE_USER = 'receive_user'
export const RECEIVE_TOKEN = 'receive_token'
export const RECEIVE_COACHES = 'receive_coaches'
export const ADD_COACH = 'add_coach'
export const UPDATE_COACH = 'update_coach'
export const DELETE_COACH= 'delete_coach'
